In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("0000000000002417_training_boston_x_y_train.csv")
df = pd.DataFrame(data)
df

# CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0   -0.407850 -0.487722 -1.266023 -0.272599 -0.576134  1.239974  0.840122   
1   -0.407374 -0.487722  0.247057 -0.272599 -1.016689  0.001946 -0.838337   
2    0.125179 -0.487722  1.015999 -0.272599  1.367490 -0.439699  0.687212   
3    0.028304 -0.487722  1.015999 -0.272599  1.859875 -0.047918  0.801005   
4   -0.412408 -0.487722 -0.969827 -0.272599 -0.913029 -0.384137 -0.834781   
..        ...       ...       ...       ...       ...       ...       ...   
374 -0.204929 -0.487722  1.231945  3.668398  0.434551  2.161728  1.053485   
375  0.231398 -0.487722  1.015999 -0.272599  1.367490  0.215644  0.687212   
376 -0.408311 -0.487722  0.247057 -0.272599 -1.016689 -0.206055 -0.809889   
377 -0.410620 -0.487722 -1.152214 -0.272599 -0.818007  0.068904 -1.826921   
378  0.342909 -0.487722  1.015999  3.668398  0.659147  1.041946  1.028593   

          DIS       RAD       TAX   PTRATIO         B     LSTAT     Y  
0   -0.520264 -0.752922 -1.278354 -0.303094  0.410571 -1.097990  37.9  
1    0.336351 -0.523001 -0.060801  0.113032  0.291169 -0.520474  21.4  
2   -0.577309  1.661245  1.530926  0.806576 -3.795795  0.891076  12.7  
3   -0.712836  1.661245  1.530926  0.806576 -0.066050  0.215438  19.9  
4    0.300508 -0.752922 -0.957633  0.020560  0.431074  0.029007  22.5  
..        ...       ...       ...       ...       ...       ...   ...  
374 -0.833960 -0.523001 -0.031105 -1.736418  0.361122 -1.504494  50.0  
375 -0.703186  1.661245  1.530926  0.806576 -2.812183  0.499991  14.3  
376  0.140451 -0.523001 -0.060801  0.113032  0.332066 -0.334043  20.8  
377  0.674814 -0.637962  0.129256 -0.719220  0.203235 -0.744752  22.6  
378 -1.232462  1.661245  1.530926  0.806576  0.387875 -1.358713  50.0  

[379 rows x 14 columns]

In [3]:
x = df.iloc[:, 0:13]
y = df.iloc[:, 13:14]

In [4]:
# from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [5]:
# x_train, x_test, y_train, y_test = train_test_split(x, y) 

In [6]:
algo = LinearRegression()

In [7]:
algo.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
m = algo.coef_
c = algo.intercept_

In [9]:
m

array([[-0.93808077,  0.74103443,  0.01169157,  0.78087372, -2.1745575 ,
         2.35429653,  0.1233381 , -2.95232355,  2.53296817, -1.7029037 ,
        -2.25151962,  0.58835429, -4.26368155]])

In [10]:
c

array([22.67723326])

In [11]:
name = [ "CRIM","ZN","INDUS","CHAS","NOX","RM","AGE","DIS","RAD","TAX","PTRATIO","B","LSTAT"]
new_data = pd.read_csv("0000000000002417_test_boston_x_test.csv", names= name)
nd = pd.DataFrame(new_data)
nd

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0    2.918166 -0.487722  1.015999 -0.272599  0.365444 -1.609343  1.117494   
1   -0.403392 -0.487722  0.406098 -0.272599 -1.016689  0.560412 -1.332629   
2   -0.413178 -0.487722  0.115738 -0.272599  0.158124 -0.234548  0.288933   
3   -0.412649  0.413589 -0.802031 -0.272599 -0.999412 -0.408356 -1.677566   
4   -0.405882 -0.487722 -0.375976 -0.272599 -0.299707 -0.127698 -0.504068   
..        ...       ...       ...       ...       ...       ...       ...   
122 -0.408684 -0.487722  0.247057 -0.272599 -1.016689 -0.585014 -1.137046   
123 -0.408903 -0.487722  0.406098 -0.272599 -1.016689 -0.392685 -0.934351   
124 -0.410014  2.087452 -1.378373 -0.272599 -1.241285 -0.570767 -1.780692   
125 -0.403176 -0.487722 -0.375976 -0.272599 -0.299707 -0.224575  0.591198   
126 -0.133563 -0.487722  1.231945 -0.272599  2.732346 -1.442658  0.904131   

          DIS       RAD       TAX   PTRATIO         B     LSTAT  
0   -1.048494  1.661245  1.530926  0.806576 -1.597551  1.041062  
1    1.029344 -0.637962 -0.708183 -1.135347  0.441052 -0.894738  
2   -0.716639 -0.982843 -0.803212  1.176466  0.441052 -0.500850  
3    1.435452 -0.637962 -0.981390 -0.765457  0.441052 -0.591963  
4   -0.483566 -0.523001 -0.143951  1.130230  0.403663  0.048631  
..        ...       ...       ...       ...       ...       ...  
122  0.336351 -0.523001 -0.060801  0.113032  0.431842 -0.498046  
123  0.811768 -0.637962 -0.708183 -1.135347  0.441052 -0.315820  
124  3.287300 -0.637962  0.016409 -0.071913  0.390945 -0.681674  
125 -0.795123 -0.523001 -0.143951  1.130230  0.340070  0.201421  
126 -0.978615 -0.523001 -0.031105 -1.736418 -2.938931  0.488777  

[127 rows x 13 columns]

In [16]:
new_pred = algo.predict(nd)
new_pred

array([[12.43328344],
       [29.03367318],
       [22.37164455],
       [24.47778655],
       [20.60166977],
       [ 2.72533175],
       [30.40000409],
       [24.86120042],
       [18.65724977],
       [23.53985838],
       [24.11396872],
       [17.71143854],
       [17.44000298],
       [21.65356278],
       [42.31137694],
       [23.84974493],
       [24.47573232],
       [27.53872655],
       [20.23606694],
       [31.15155453],
       [23.78237904],
       [25.00979443],
       [33.95768541],
       [36.43515649],
       [32.04098329],
       [16.71322632],
       [23.47176611],
       [32.93828009],
       [25.1807008 ],
       [33.71008685],
       [16.88580202],
       [26.02760837],
       [23.27040025],
       [25.47758968],
       [15.00946631],
       [29.5857494 ],
       [26.24821245],
       [20.37245654],
       [24.43681498],
       [ 9.44706894],
       [ 8.38096654],
       [29.01392345],
       [29.59085403],
       [19.7575697 ],
       [20.3719679 ],
       [ 3

In [13]:
new_pred[2]

array([22.37164455])

In [58]:
import csv
with open('New_Prediction_Boston.csv', 'w') as f:
    for c in range(len(new_pred)):
        e = new_pred[c][0]
        d = round(e, 7)
        f.write(str(d))
        f.write("\n")